spring.application.name=basic-spring-boot
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@//amanda-db-host:1521/AMANDA
spring.datasource.username=${AMANDA_DB_USERNAME}
spring.datasource.password=${AMANDA_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
